name: google_geocoding_plus
description: A new Flutter package for handle google geocoding api that geocoding and reverse geocoding requests are available, forked from https://github.com/bazrafkan
version: 1.0.0
homepage: https://github.com/phungtp97/google_geocoding_plus

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
